### ISSUE TITLE
Selfie contracts not working

### ISSUE THREAD

**Issue by RachelPriss** [whale2/KourageousTourists#1]
When tourists trying to shot selfie, interface hides, shutter sound plays, message "Selfie taken!" appears, but... it's all. The contract still not completed.

Logfile fragment:
```
[LOG 09:48:59.921] [UIMasterController]: HideUI
[LOG 09:48:59.937] KT: TakeSelfie:0: Selfie
[ERR 09:48:59.937] Exception handling event Selfie in class KourageousSelfieParameter:System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[ProtoCrewMember].get_Item (Int32 index) [0x00000] in <filename unknown>:0
  at KourageousTourists.KourageousSelfieParameter.onSelfieTaken () [0x00000] in <filename unknown>:0
  at EventVoid.Fire () [0x00000] in <filename unknown>:0

[EXC 09:48:59.937] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
        System.Collections.Generic.List`1[ProtoCrewMember].get_Item (Int32 index)
        KourageousTourists.KourageousSelfieParameter.onSelfieTaken ()
        EventVoid.Fire ()
        UnityEngine.Debug:LogException(Exception)
        EventVoid:Fire()
        KourageousTourists.KourageousTouristsAddOn:TakeSelfie()
        BaseEvent:Invoke()
        UIPartActionButton:OnClick()
        UnityEngine.EventSystems.EventSystem:Update()
[ERR 09:48:59.937] Exception handling event Selfie in class KourageousSelfieParameter:System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[ProtoCrewMember].get_Item (Int32 index) [0x00000] in <filename unknown>:0
  at KourageousTourists.KourageousSelfieParameter.onSelfieTaken () [0x00000] in <filename unknown>:0
  at EventVoid.Fire () [0x00000] in <filename unknown>:0

[EXC 09:48:59.937] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
        System.Collections.Generic.List`1[ProtoCrewMember].get_Item (Int32 index)
        KourageousTourists.KourageousSelfieParameter.onSelfieTaken ()
        EventVoid.Fire ()
        UnityEngine.Debug:LogException(Exception)
        EventVoid:Fire()
        KourageousTourists.KourageousTouristsAddOn:TakeSelfie()
        BaseEvent:Invoke()
        UIPartActionButton:OnClick()
        UnityEngine.EventSystems.EventSystem:Update()
[LOG 09:49:00.343] [UIMasterController]: ShowUI
[LOG 09:49:01.937] KT: FixedUpdate:0: Getting snd
[LOG 09:49:01.937] KT: getOrCreateAudio:0: returning audio from cache
[LOG 09:49:01.937] KT: FixedUpdate:0: wrting file ../Screenshots/╨Р╤А╤Б╨░ ╨Ъ╨╡╤А╨╝╨░╨╜-Mun-18-02-06-09:49:01.png
[LOG 09:49:05.937] [UIMasterController]: ShowUI
```

**Comment by whale2** [comment]
Didn't encounter that yet. Could you please post a screenshot of the contract?

**Comment by RachelPriss** [comment]
There's screenshots and save:

![screenshot228](https://user-images.githubusercontent.com/17809851/35989636-94abf890-0cf9-11e8-9a1d-84528863a258.png)

![screenshot227](https://user-images.githubusercontent.com/17809851/35989637-953311c2-0cf9-11e8-88be-86e412bb07a2.png)

[persistent.sfs.txt](https://github.com/whale2/KourageousTourists/files/1708233/persistent.sfs.txt)

If you need something else, just say. It's a really good and interesting mod (at last near-Kerbin orbital station became meaningful!!!) and I want it to be glitch-less.

Also, if you want add to your mod a Russian translation, I can help.

**Comment by whale2** [comment]
Could you please try this one?

[KourageousTourists-0.4.1-rc.zip](https://github.com/whale2/KourageousTourists/files/1711953/KourageousTourists-0.4.1-rc.zip)

Regarding translation, the code should be adapted for localization. As soon as I make it - you're welcome.

**Comment by RachelPriss** [comment]
I tried. Now selfie contracts looks like this:   

![screenshot230](https://user-images.githubusercontent.com/17809851/36165061-3d1e6d6a-10e6-11e8-8fae-801309d372dc.png)

:(

**Comment by whale2** [comment]
I'm not sure where it comes from, I'll take a look. What was supposed to be changed in that pre-release is addressing the case when no one left inside the ship at the moment of taking a selfie. There clearly was a bug there, but could be some more.

**Comment by whale2** [comment]
Sorry, this took so long. Just checked with your save and Russian KSP 1.3.1. Contract text in Mission Control fixed. Selfie taken and contract completed after recovering on Kerbin.
Please take 0.4.1 from Releases page.
Closing, please reopen if it doesn't work for you.
